version: '3.8'

services:
  functiongemma:
    image: public.ecr.aws/b8k9c8n5/openmind/functiongemma_service:v1.0.1
    container_name: functiongemma

    network_mode: host
    runtime: nvidia

    ports:
      - "8200:8200"

    gpus:
      - driver: nvidia
        count: 1
        capabilities: [gpu]

    shm_size: "4g"
    ulimits:
      memlock: -1
      stack: 67108864

    restart: unless-stopped
