version: '3.8'

services:
  kokoro_tts:
    image: openmindagi/kokoro-fastapi:latest
    container_name: kokoro_tts

    network_mode: host
    runtime: nvidia

    ports:
      - "8880:8880"

    environment:
      - PYTHONPATH=/app:/app/api
      - USE_GPU=true
      - PYTHONUNBUFFERED=1
      - API_LOG_LEVEL=DEBUG

    gpus:
      - driver: nvidia
        count: 1
        capabilities: [gpu]

    shm_size: "8g"
    ulimits:
      memlock: -1
      stack: 67108864

    restart: unless-stopped
