services:
  riva_speech:
    image: openmindagi/riva-speech-server:2.24.0-l4t-aarch64
    container_name: riva_speech
    restart: unless-stopped

    ipc: host
    runtime: nvidia

    ports:
      - "6790:6790"
      - "6791:6791"

    environment:
      - RIVA_SERVER_HTTP_PORT=50000
      - NMT_REMOTE_ASR_SERVICE=0.0.0.0:50051
      - NMT_REMOTE_TTS_SERVICE=0.0.0.0:50051
      - LD_PRELOAD=
      - RIVA_API_KEY=${RIVA_API_KEY}
      - RIVA_API_NGC_ORG=${RIVA_API_NGC_ORG:-openmind-1}
      - RIVA_EULA=${RIVA_EULA:-accept}
      - PYTHON_ARGS=--server-mode --ws-host=0.0.0.0 --http-host=0.0.0.0 --start-history=150 --start-threshold=0.50 --stop-history-eou=400 --stop-threshold-eou=0.85 --stop-history=800 --stop-threshold=0.92 --automatic-punctuation --boosted-lm-words OpenMind --boosted-lm-words Bits --boosted-lm-words hello --boosted-lm-words GTC --boosted-lm-words Unitree --boosted-lm-words robot --boosted-lm-words OM1 --boosted-lm-words NVIDIA --boosted-lm-score 100.0
      - GLOG_minloglevel=2

    volumes:
      - /home/openmind/riva_quickstart_arm64_v2.24.0/model_repository:/data

    devices:
      - /dev/bus/usb:/dev/bus/usb:rwm
      - /dev/snd:/dev/snd:rwm

    gpus:
      - driver: nvidia
        count: 1
        capabilities: [gpu]

    shm_size: "8g"
    ulimits:
      memlock: -1
      stack: 67108864

    security_opt:
      - label:disable
