version: '3.8'

services:
  zenoh_bridge:
    build:
      context: .
    image: openmindagi/unitree_sdk:latest
    container_name: zenoh_bridge
    network_mode: host
    privileged: true
    environment:
      - ROS_DISTRO=humble
    command: "zenoh-bridge-ros2dds -c /app/unitree_sdk/zenoh/zenoh_bridge_config.json5"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
