version: '3.8'

services:
  ota_updater:
    build:
      context: ..
      dockerfile: ./OTA/Dockerfile
    image: openmindagi/ota:v1.0.1-beta.1
    container_name: ota_updater
    restart: unless-stopped
    environment:
      - OM_API_KEY=${OM_API_KEY}
      - OM_API_KEY_ID=${OM_API_KEY_ID}
      - OM1_COMMAND=${OM1_COMMAND:-unitree_go2_modes}
      - ROBOT_TYPE=${ROBOT_TYPE:-go2}
      - HOST_USER_ID=${HOST_USER_ID:-2001}
      - OTA_UPDATER_SERVER_URL=${OTA_UPDATER_SERVER_URL:-wss://api.openmind.org/api/core/ota/updater}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/local/bin/docker:ro
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose:ro
      - ./.ota:/app/.ota
    network_mode: host
    command: python -m OTA.updater.main
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
