version: '3.8'

services:
  om1:
    build:
      context: .
      dockerfile: Dockerfile
    image: openmindagi/om1:v1.0.0
    container_name: om1
    restart: unless-stopped
    network_mode: host
    env_file:
      - /app/.ota/om1_v1.0.0.env
    environment:
      - ROS_DOMAIN_ID=0
      - CYCLONEDDS_HOME=/app/cyclonedds/install
      - CYCLONEDDS_URI=file:///app/OM1/cyclonedds/cyclonedds.xml
      - CMAKE_PREFIX_PATH=/app/cyclonedds/install
      - OM_API_KEY=${OM_API_KEY}
      - VIRTUAL_ENV=/app/OM1/.venv
      - PATH=/app/OM1/.venv/bin:$PATH
      - XDG_RUNTIME_DIR=/run/user/2002
      - PULSE_SERVER=unix:/run/user/2002/pulse/native
      - PULSE_COOKIE=/root/.config/pulse/cookie
      - ALSA_CARD=0
    volumes:
      - /home/openmind/om1/om1/config:/app/OM1/config
      - /dev/snd:/dev/snd:rw
      - /run/user/2002/pulse:/run/user/2002/pulse:rw
      - /home/openmind/.config/pulse/cookie:/root/.config/pulse/cookie:ro
    devices:
      - /dev/snd:/dev/snd
      - /dev/video0:/dev/video0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
    security_opt:
      - apparmor:unconfined
    group_add:
      - audio
    command: ["${OM1_COMMAND:-unitree_go2_modes}"]
