version: '3.8'

services:
  ota_agent:
    build:
      context: ..
      dockerfile: ./OTA/Dockerfile
    image: openmindagi/ota:v1.0.0
    container_name: ota_agent
    restart: unless-stopped
    environment:
      - OM_API_KEY=${OM_API_KEY}
      - OM_API_KEY_ID=${OM_API_KEY_ID}
      - OM1_COMMAND=${OM1_COMMAND:-unitree_go2_modes}
      - ROBOT_TYPE=${ROBOT_TYPE:-go2}
      - OTA_AGENT_SERVER_URL=${OTA_AGENT_SERVER_URL:-wss://api.openmind.org/api/core/ota/agent}
      - DOCKER_STATUS_URL=${DOCKER_STATUS_URL:-https://api.openmind.org/api/core/ota/agent/docker}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/local/bin/docker:ro
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose:ro
      - /home/openmind/.ota:/app/.ota
    network_mode: host
    command: python -m OTA.agent.main
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
