services:
  text_embedding:
    image: openmindagi/embedding_service:e5-small-v2-aarch64
    container_name: text_embedding
    restart: unless-stopped

    ipc: host
    runtime: nvidia

    ports:
      - "8100:8100"

    gpus:
      - driver: nvidia
        count: 1
        capabilities: [gpu]
